
import AsyncStorage from '@react-native-async-storage/async-storage';

const CONFIG_lang = {
	fitness_vi :{
		"Coach": "HLV",
		"AppName": "Fitlive",
		"BookSession": "Đặt lịch",
		"Calendar":"Lịch",
		"AddClient":"Thêm khách hàng",
		"Clients":"DS Khách hàng",
		"Coach":"DS Nhân viên",
		"AddLocation":"Thêm địa chỉ",
		"Setting":"Cài đặt",
		"LogIn":"Đăng nhập",
		"Password":"Mật khẩu",
		"DontHaveAccount":"Chưa có tài khoản?",
		"CreateAccount":"Đăng ký ngay!",
		"Create":"Tạo",
		"FirstName":"Họ và tên đệm",
		"LastName":"Tên",
		"ClientPhone":"Số điện thoại khách hàng",
		"ClientEmail":"Email khách hàng",
		"Add":"Thêm",
		"SelectAClient":"Chọn khách hàng",
		"Search":"Tìm",
		"SelectLocation":"Chọn địa điểm",
		"SelectTime":"Chọn thời gian",
		"HowManySession":"Số session",
		"HowManyMember":"Số người tham gia",
		"SessionType":"Loại session",
		"SearchBooking":"Quản lý Session",
		"BusinessSetting":"Cài đặt doanh nghiệp",
		"BookNew":"Đặt lịch",
		"ClientId":"ID khách hàng",
		"AddColleage":"Thêm nhân viên",
		"CoachId":"Mã nhân viên",
		"Optional":"Không bắt buộc",
		"Client":"Khách hàng",
		"Location":"Địa điểm",
		"CoachAssign":"HLV chỉ định",
		"NoOfMember":"Số thành viên",
		"NoOfSession":"Số session",
		"CreatedById":"Tạo bởi",
		"StartSession":"Bắt đầu Session",
		"CancelSession":"Hủy Session",
		"Detail":"Chi tiết",
		"CreateOrder":"Tạo đơn hàng",
		"SearchClientInCompany":"Tìm khách hàng trong hệ thống",
		"ClientAssign":"Khách hàng chỉ định",
		"OrderId":"Mã đơn hàng",
"ProductName":"Tên sản phẩm",
"UnitPrice":"Đơn giá",
"Quantity":"Số lượng",
"CommissionRate":" Tỉ lệ hoa hồng",
"OrderNote":"Lưu ý cho đơn hàng",
"ChangePassword":"Đổi mật khẩu",
"Language":"Ngôn ngữ",
"RepeatPassword":"Nhập lại mật khẩu",
"NameOfYourBusiness":"Tên doanh nghiệp",
"BusinessAddress":"Địa chỉ doanh nghiệp",
"YourName":"Tên của bạn",
"YourPhone":"Số điện thoại của bạn",
"YourEmail":"Email của bạn",
"LogOut":"Đăng xuất",
"Loading":"Đang tải...",
"NoClient":"Chưa có khách hàng",
"LocationAssign":"Địa điểm chỉ định",
"ViewAllCompanySession":"Xem toàn bộ session của công ty",
"ViewAllCompanyClient":"Xem toàn bộ khách hàng của công ty",
"AddSession":"Thêm Session",
"ConfirmSession":"Xác nhận Session",
"ConfirmSessionOfLocation":"Xác nhận Session theo địa điểm chỉ định",
"Name":"Tên",
"Role":"Chức vụ",
"Phone":"Số điện thoại",
"ClientCode":"Mã khách hàng",
"AppUpdate":"Cập nhật ứng dụng",
"TryMobileApp":"Dùng phiên bản ứng dụng Mobile",
"BetterExperience":"Để trải nghiệm tốt hơn",
"DownloadIosApp":"Tải IOS App",
	},
	fitness_en :{
		"Coach": "Coach",
		"AppName": "Fitlive",
		"BookSession": "Book Session",
		"Calendar":"Calendar",
		"AddClient":"Add Client",
		"Clients":"Clients",
		"Coach":"Coach",
		"AddLocation":"Add Location",
		"Setting":"Setting",
		"LogIn":"Log In",
		"Password":"Password",
		"DontHaveAccount":"Don't have account?",
		"CreateAccount":"Create Account!",
		"FirstName":"First Name",
		"LastName":"Last Name",
		"ClientPhone":"Client Phone",
		"ClientEmail":"Client Email",
		"Add":"Add",
		"SelectAClient":"Select A Client",
		"Search":"Search",
		"SelectLocation":"Select Location",
		"SelectTime":"Select Time",
		"HowManySession":"How many session",
		"HowManyMember":"How many member",
		"SessionType":"Session type",
		"SearchBooking":"Search Booking",
		"BusinessSetting":"Business Setting",
		"BookNew":"Book New",
		"ClientId":"Client Id",
		"AddColleage":"Add Colleage",
		"CoachId":"Coach Id",
		"Optional":"Optional",
		"Client":"Client",
		"Location":"Location",
		"CoachAssign":"Coach Assign",
		"NoOfMember":"No Of Member",
		"NoOfSession":"No Of Session",
		"CreatedById":"Created By Id",
		"StartSession":"Start Session",
		"CancelSession":"Cancel Session",
		"Detail":"Detail",
		"CreateOrder":"Create Order",
		"SearchClientInCompany":"Search Client In Company",
		"ClientAssign": "Client Assign",
"OrderId":"Mã đơn hàng",
"ProductName":"Product Name",
"UnitPrice":"Unit Price",
"Quantity":"Quantity",
"CommissionRate":"Commission Rate",
"OrderNote":"Order Note",
"ChangePassword":"Change Password",
"Language":"Language",
"RepeatPassword":"Repeat Password",
"NameOfYourBusiness":"Name Of Your Business",
"BusinessAddress":"Business Address",
"YourName":"Your Name",
"YourPhone":"Your Phone",
"YourEmail":"Your Email",
"LogOut":"Log Out",
"Loading":"Loading...",
"NoClient":"No clients",
"LocationAssign":"Location Assign",
"ViewAllCompanySession":"View all company Session",
"ViewAllCompanyClient":"View all company Client",
"AddSession":"Add Session",
"ConfirmSession":"Confirm Session",
"ConfirmSessionOfLocation":"Confirm Session Of Location",
"ClientCode":"Client Code",
"AppUpdate":"App Update",
"TryMobileApp":"Try Mobile App",
"BetterExperience":"For better experience",
"DownloadIosApp":"Download IOS App",

	}
}
let typeLang;
let language;
 const getLanguage = async () => {
      language = await AsyncStorage.getItem('language');
      console.log('lang ', language);
      if (language == 'null') language = 'vi'

  };

export const lang = (key)=>{
	if(!language){
		language = 'vi'
		getLanguage();
	}
	var typeLang = 'fitness_'+language

	if(CONFIG_lang[typeLang] && CONFIG_lang[typeLang][key]) return CONFIG_lang[typeLang][key]
	else return key

}


